/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

public class Main {
    public static void main(String[] args) {
        int limit = 4000000;
        int current = 1;
        int nextCurrent = 2;
        long sum = 0;

        do {
            int next = current + nextCurrent;

            if (current % 2 == 0) {
                sum += current;
            }

            System.out.println(current);

            current = nextCurrent;
            nextCurrent = next;

        } while (current <= limit);
        System.out.println("Sum of even number in the sequence is: " + sum);
    }
}